services:
  app:
   container_name: app
   command:
     - poetry
     - run
     - uvicorn
     - app.main:app
     - --host=0.0.0.0
     - --port=8000
     - --log-level=debug
   build:
     context: .
     dockerfile: Dockerfile
   restart: always
   ports:
     - "8000:8000"
